POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Pedro"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Pedro",
  "number":"23233232"
}
